[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha5"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[platform.java11.dependency]]
path = "./lib/poi-5.0.0.jar"
artifactId = "poi"
groupId = "apache"
version = "5.0.0"

[[platform.java11.dependency]]
path = "./lib/poi-ooxml-5.0.0.jar"
artifactId = "poi-ooxml"
groupId = "apache"
version = "5.0.0"


