[package]
org = "malepathirana"
name = "ballerina_excel_library"
version = "0.1.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../excel-native/build/libs/excel-native-0.1.0-SNAPSHOT-all.jar"
groupId = "malepathirana"
artifactId = "excel-native"
version = "0.1.0-SNAPSHOT"
